### ISSUE TITLE
Plugin crashes when FreeCAD is not installed

### ISSUE THREAD

**Issue by ChrisTerBeke** [thopiekar/CuraFreeCadPlugin#2]
```
2017-11-29 11:51:39,152 - ERROR - UM.Logger.logException [76]: Exception: Error loading plugin CuraFreeCadPlugin:
2017-11-29 11:51:39,154 - ERROR - UM.Logger.logException [80]: Traceback (most recent call last):
2017-11-29 11:51:39,154 - ERROR - UM.Logger.logException [80]:   File "C:\msys64\home\c.terbeke\code\github\Uranium\UM\PluginRegistry.py", line 225, in loadPlugin
2017-11-29 11:51:39,155 - ERROR - UM.Logger.logException [80]:     to_register = plugin.register(self._application)
2017-11-29 11:51:39,155 - ERROR - UM.Logger.logException [80]:   File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraFreeCadPlugin\CuraFreeCadPlugin\__init__.py", line 29, in register
2017-11-29 11:51:39,156 - ERROR - UM.Logger.logException [80]:     return {"mesh_reader": FreeCADReader.FreeCADReader()}
2017-11-29 11:51:39,156 - ERROR - UM.Logger.logException [80]:   File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraFreeCadPlugin\CuraFreeCadPlugin\FreeCADReader.py", line 21, in __init__
2017-11-29 11:51:39,157 - ERROR - UM.Logger.logException [80]:     self.scanForAllPaths()
2017-11-29 11:51:39,157 - ERROR - UM.Logger.logException [80]:   File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraFreeCadPlugin\CuraFreeCadPlugin\CadIntegrationUtils\CommonCLIReader.py", line 56, in scanForAllPaths
2017-11-29 11:51:39,157 - ERROR - UM.Logger.logException [80]:     path = self._findPathFromExtension(file_extension)
2017-11-29 11:51:39,158 - ERROR - UM.Logger.logException [80]:   File "C:\Users\c.terbeke\AppData\Roaming\cura\master\plugins\CuraFreeCadPlugin\CuraFreeCadPlugin\CadIntegrationUtils\CommonCLIReader.py", line 62, in _findPathFromExtens
ion
2017-11-29 11:51:39,158 - ERROR - UM.Logger.logException [80]:     file_class = winreg.QueryValue(winreg.HKEY_CLASSES_ROOT, extension)
2017-11-29 11:51:39,159 - ERROR - UM.Logger.logException [80]: FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by thopiekar** [comment]
Good catch! Will fix that in CIU and then the same issue should also be fixed for https://github.com/thopiekar/CuraOpenSCADPlugin/issues/3 and https://github.com/thopiekar/CuraBlenderPlugin/issues/5 .
